general:
  initial_teleop_mode: teleop_mode
  #  initial_teleop_mode: manual_mode

  states:

    sequences:
      priority_level_1: []
    parallels:
       priority_level_1: []
    ss_drivetrain:
      priority_level_1: []
      default: [ st_drivetrain ]


  subsystems: [ ss_drivetrain ]

  input_booleans: []

  # add the joysticks here
  input_numerics: [ipn_driver_left_x, ipn_driver_left_y]

  input_vectors: [ ipv_power_distribution_panel ]

  # add the drivetrain motors here
  output_numerics: [ opn_drivetrain_front_right_speed, opn_drivetrain_front_left_speed,
                     opn_drivetrain_back_left_speed, opn_drivetrain_back_right_speed,
                     opn_drivetrain_front_right_angle_motor, opn_drivetrain_front_left_angle_motor,
                     opn_drivetrain_back_left_angle_motor, opn_drivetrain_back_right_angle_motor]

  output_booleans: []


global_timing:
  frame_time_threshold_input_service: 80
  frame_time_threshold_logging_service: 80
  frame_time_threshold_output_service: 80
  frame_time_threshold_state_service: 80
  frame_time_threshold_webdashboard_service: 80
  frame_cycle_time_threshold_core_thread: 80
  frame_cycle_time_threshold_info_thread: 80

# add joysticks for the drivetrain here
global_drivetrain:
  drive_axis: ipn_driver_left_y
  rotate_axis: ipn_driver_left_x


log:
#  ips_selected_auto: true

global_webdashboard:

  auto_selector:
    origins: []
    destinations: []
    actions: []

  match_values:

global_pneumatics:
  #CTREPCM or REVPH
  module_type: CTREPCM
  #CTREPCM: 0
  #REVPH: 21
  device_id: 0


